# Funding

This project is maintained in spare time. If you find it useful, consider supporting its development:

- [Buy Me a Coffee](https://www.buymeacoffee.com/michak)
# - [GitHub Sponsors](https://github.com/sponsors/michakfromparis)
# - [Ko-fi](https://ko-fi.com/michakfromparis)

Thank you! ❤️
